### ISSUE TITLE
support owner-form for extends form

### ISSUE THREAD

**Issue by gagaboy** [moqui/moqui-runtime#106]
When I define a form-single and extends from another form and use owner-form to submit,I found that the extends form part is disabled.
And I think it maybe change in DefaultScreenMarcros.html.ftl(line 578)  and DefaultScreenMarcros.vuet.ftl(line 371) with the code below:
`<fieldset class="form-horizontal"<#if urlInstance.disableLink> disabled="disabled"</#if>>
`

change to
` <fieldset class="form-horizontal"<#if !urlInstance.disableLink || ownerForm?has_content> <#else>disabled="disabled"</#if>>`

**Comment by jonesde** [comment]
Wouldn't this break fields that should be disabled on forms with an ownerForm?

The question is why did those fields get disabled in the first place. It may be that the transition isn't valid or the user doesn't have authorization to call it, or a read-only authorization is in place for it, or certain other reasons. Anyway, the root cause needs to be found and not something like this which makes it impossible to disable fields in a form-single with owner-form.

BTW, there are various issues with the owner-form concept... use at your own risk. I've considered removing it just because there are so many caveats and people expect it to do things more similar to the extends attribute, but that's not what it is. For example separate form-single forms don't know anything about eachother, ever, not even if owner-form is used.
