### ISSUE TITLE
AutoScreen does not create transitions

### ISSUE THREAD

**Issue by okroener** [moqui/moqui-runtime#120]
AutoFind.xml does not generate the necessary transitions and does also not create the dialogs in the current version.

I have added some support for this, and I would be happy to publish the code.

I have just created a pull request for review, thx

Oliver

**Comment by jonesde** [comment]
The XML output of the auto screens is not meant to be used as-is, and in fact doing so would be a strong counter pattern (or 'worst' practice). These are meant only to be used as a starting point when creating new screens, to be modified as needed for what you actually want on your screen.

One aspect of that is usability but more important is security and system integrity. The automatic services (implicitly defined based on entity definitions) both open security holes and allow manual changes that should not generally be allowed. As a general architecture principle in Mantle USL, for example, if a service exists to do the update that should be used in the UI and/or REST/etc API instead of the entity auto service. In other words when building a screen the developer needs to choose which services to call or in general how to handle input from the user and the default in the auto screens is NOT generally recommended and shouldn't be generally relied on.
