### ISSUE TITLE
Upgrade elFinder

### ISSUE THREAD

**Issue by newmann** [moqui/moqui-runtime#218]
https://github.com/Studio-42/elFinder

WARNING: IF YOU HAVE OLDER (IN PARTICULAR 2.1.61 OR EARLIER) VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER.

base-component/tools/screen/System/Resource/ElFinder.xml
now is 2.1.56, should upgrade to 2.1.62

**Comment by jonesde** [comment]
I went ahead and updated the ElFinder client libraries to 2.1.62, but it looks like it was not strictly needed. The warning in the README didn't say exactly what the issue was, and while an issue was filed it had no details (out of security precaution, though nice to add them once patched, like in a CVE), but I did find a commit about a security issue. Based on that it was not an issue for Moqui because we do not use the server-side PHP code and the security fix made was for path traversal in the PHP code. Moqui uses only the client-side JS/CSS and has its own server-side implementation in Java (that uses the Moqui ResourceFacade to simulate a filesystem).
