### ISSUE TITLE
Unable to delete dbresource using ElFinder

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-runtime#23]
A JavaScript error is thrown when I attempt to delete a resource using the ElFinder. To reproduce, try to upload a ExampleContent file and then try to delete the dbresource using ElFinder. I tried this on Firefox v45.

`TypeError: e.isRejected is not a function`

**Comment by jonesde** [comment]
I didn't get the same error, but did find that rm wasn't working (data coming in different than in the past) and upload had a bug (worked but didn't return the response ElFinder expects for added file(s)).

The main fixes were in moqui-framework commit #200cd61 (the server side connector for ElFinder is in moqui-framework rather than moqui-runtime). In moqui-runtime I also updated ElFinder to 2.1.11, though that didn't fix anything related to this.
