### ISSUE TITLE
[vuejs] on Windows 10 with latest clone from github, Chrome vapps does not render 

### ISSUE THREAD

**Issue by ashokraman** [moqui/moqui-runtime#76]
![image](https://cloud.githubusercontent.com/assets/2268806/22237841/46646c62-e234-11e6-812b-ff74ae232ab0.png)
Thanks,
Ashok

**Comment by jonesde** [comment]
It looks like the second error is caused by the first (the 'moqui' object hasn't been defined yet). The root cause is the error parsing ConbinedBaseMin.min.js.

I don't have a Windows machine to reproduce this on, and haven't seen it on Chrome in Linux or on Mac OS, but that is where to start. Note that this is a big combined JS file created by a Gradle task in the runtime/base-component/webroot/build.gradle file. You could try it with the combined but no minified file, and be sure to check that the webroot gradle build was successful and such.

**Comment by ashokraman** [comment]
With minimal gradlew experience, I undid the minimization like this - 

task minifyMoquiLib(type: Copy) {
    from file("${webrootPath}/js/MoquiLib.js")
    into file("${webrootPath}/js")
	rename { String fileName ->
        fileName.replace('MoquiLib', 'MoquiLib.min')
    }
    closure { compilerOptions.setOutputCharset(StandardCharsets.UTF_8) }
}
and
task minifyCombinedBase(type: Copy) {
    dependsOn combineBaseJs
    from file("${webrootPath}/js/CombinedBase.min.js")
    into file("${webrootPath}/js")
	rename { String fileName ->
        fileName.replace('CombinedBase', 'CombinedBaseMin')
    }
    closure {
        warningLevel = 'QUIET'
        compilerOptions.setOutputCharset(StandardCharsets.UTF_8)
    }
}

With that it seems to work as expected. 

Thanks,
Ashok

**Comment by jonesde** [comment]
Yes, best to keep this open.

Based on your reply it appears that the minification done with the Google Closure Compiler is causing issues so some library or other included in the big CombinedBase file, at least in Chrome on Windows 10.

For future reference: A better solution than changing the build file is to change the apps.xml file and the vapps.xml file to use the pre-minify CombinedBase.min.js (instead of CombinedBaseMin.min.js). Actually the apps.xml file is already using the pre-minify CombinedBase.min.js, so this should only be an issue under /vapps.

It may be that there are other minify settings that would resolve this, but without a test platform that is tough for me to do...

**Comment by jonesde** [comment]
The minifyCombinedBase task in the build.gradle file is disabled and the vapps.xml screen now uses CombinedBase.min.js (instead of CombinedBaseMin.min.js) to resolve this issue, though it does add a bit to the size of the JS downloaded on non-cached page loads.
