### ISSUE TITLE
CombinedBase.min.js - invalid regular expression: Nothing to repeat

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#83]
I noticed an error in browser's console. It's related to CombinedBase JS library. Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/14863763/25369491/7f731a16-2984-11e7-8d81-5bc1e1185feb.png)

**Comment by jonesde** [comment]
I looked into this a while back and it is part of a third party library we are using, don't remember which one (the CombinedBase.min.js file is mostly just third party libraries combined into one). I haven't seen anything not work because of this, and figured they had a good reason for it even if Chrome complains about it (looks like that is what you're using).

**Comment by mrovnanik** [comment]
OK, got it.

**Comment by mrovnanik** [comment]
There seems to be a problem with this task in webroot's build.gradle. If compiled on my windows PC, everything works correctly.

When run on server, the file CombinedBase.min.js created by the combineJs taks is corrupted and no JS libraries work. I need to add them manually separately.

![image](https://cloud.githubusercontent.com/assets/14863763/25996537/2069cf64-3718-11e7-95db-f6cf294b2351.png)

![image](https://cloud.githubusercontent.com/assets/14863763/25996633/8fed859c-3718-11e7-9e63-ec7d0bfd0993.png)

**Comment by jonesde** [comment]
It looks like CombineJsTask uses the system file.encoding by default but can be set explicitly which is done in commit #9a5e8ec (to UTF-8).

Would you let me know if this works on your system? My guess is this is something specific to your OS or Java setup which has a different character set that was messing up the character encoding. I don't know why UTF-8 isn't the default encoding for gradle-js-plugin instead of the system default, seems like a bad idea.

**Comment by mrovnanik** [comment]
Yes, it works. Thanks for a prompt reaction.
